# Generated by Django 3.0.4 on 2020-03-26 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('country_cod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codpais')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400, verbose_name='URL Principal')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Titulo')),
                ('headline', models.TextField(blank=True, null=True, verbose_name='Encabezado')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('hash_news', models.CharField(blank=True, max_length=400, null=True, verbose_name='Hash noticia')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Country', verbose_name='Pais')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Source', verbose_name='Fuente')),
                ('tags', models.ManyToManyField(to='news.Tags', verbose_name='Tags')),
            ],
        ),
    ]
