# Generated by Django 3.0.4 on 2020-03-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
