# Generated by Django 3.0.4 on 2020-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200326_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='hash_news',
        ),
        migrations.AlterField(
            model_name='news',
            name='explanation',
            field=models.TextField(default=1, verbose_name='Cuerpo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=1, max_length=400, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
